sudo: false
language: java
jdk: 
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
script: mvn clean install

after_success:
  - cd rxjava2-jdbc
  - bash <(curl -s https://codecov.io/bash)
